---
title: "R Notebook"
output: html_notebook
---


```{r}
library(corrplot)
library(ggplot2)
library(tidyverse)
library(readxl)
library(mongolite)
library(sqldf)
```

```{r}
#cargo las bases
audio_features <- mongo(collection = "audio_features", db = "spotify_dm")
df_audio_features <- audio_features$find()

artist <- mongo(collection = "artist", db = "spotify_dm")
df_artist <- artist$find()

charts <- mongo(collection = "charts", db = "spotify_dm")
df_charts <- charts$find()
```


```{r}
#borrar duplicados
#paso 1

#saco los sub documentos que están en las columnas artists
#guardo la data en una nueva columa artist_concat
concat_column <- function(x){
appender <- c()

x <- as.data.frame(x)

if(nrow(x)==1){
  appender <- c(x[1,"id"])
}else{
    for (i in c(1:nrow(x))){
      appender <- c(x[i,"id"], appender)
      }
    appender <- sort(appender)
    }
string <- paste(appender, collapse=",")
print(string)
return(string)
}  

df_audio_features$artist_concat <- sapply(df_audio_features[,"artists"], concat_column)

#saco los sub documentos que están en la columna aviable_markets
#guardo la data en una nueva columna markets_concat


concat_column <- function(x){
appender <- c()
x <- as.data.frame(x)
for (i in c(1:nrow(x))){
  appender <- c(x[i,1], appender)
  }
appender <- sort(appender)
string <- paste(appender, collapse=",")
print (string)
return(string)
}  


df_audio_features$markets_concat <- sapply(df_audio_features[,"available_markets"], concat_column)

#me hago una copia del df para no pisarlo
df_audio_features_plano <- df_audio_features

#borro columnas "album", "artists" y "aviable markets"
df_audio_features_plano <- df_audio_features_plano[,-c(3, 12, 13)] #borro las columnas





```


```{r}
#Borro duplicados
#paso 2

#2.a: borra duplicados de audio features

nrow(df_audio_features_plano)
query = "SELECT DISTINCT * FROM df_audio_features_plano"

query_audio_features <-  sqldf(query)

nrow(query_audio_features)
head(query_audio_features)

#guardo un nuevo csv sin duplicados:
write.csv(query_audio_features, "C:/Users/igalk/OneDrive/Documentos/laburo/Data Mining FCEyN/Data mining/TP/audio_features_plano_sin_duplicados.csv", row.names = FALSE)

#2.b: borra duplicados de audio charts

query = "SELECT DISTINCT * FROM df_charts"

df_charts_sin_duplicados <- sqldf(query)

#guardo un nuevo csv sin duplicados:
write.csv(df_charts_sin_duplicados, "data/df_charts_sin_duplicados.csv", row.names = FALSE)

#2.b: borra duplicados de audio charts

query = "SELECT DISTINCT * FROM df_artist"

df_artist_sin_duplicados <- sqldf(query)

#guardo un nuevo csv sin duplicados:
write.csv(df_artist_sin_duplicados, "data/df_artist_sin_duplicados", row.names = FALSE)





```
